- name: Install OpenShift Service Mesh 3 operator
  include_tasks: ossm3-operator.yaml

- name: Install Kiali operator
  include_tasks: kiali-operator.yaml

- name: Deploy Service Mesh Ambient mode
  include_tasks: ambient-mode.yaml