# --- Service Mesh --- #
ossm_namespace: "openshift-service-mesh"
ossm_channel: "stable-3.2"

# --- GitOps --- #
output_file: /tmp/gitops-subscription.yaml
gitops_channel: latest
argocd_namespace: openshift-gitops
gitops_repo: "https://github.com/panchoraposo/ossm3-ambient-mode"