# --- Service Mesh --- #
ossm_namespace: "openshift-service-mesh"
ossm_channel: "stable-3.2"
kiali_namespace: "kiali-operator"
control_plane_namespace: "istio-system"

# --- GitOps --- #
output_file: /tmp/gitops-subscription.yaml
gitops_channel: latest
argocd_namespace: openshift-gitops
gitops_repo: "https://github.com/panchoraposo/ossm3-ambient-mode"

# --- Observability --- #
observability_namespace: observability
tempo_namespace: openshift-tempo-operator